name: R-tests

on: push

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
      NOAA_TOKEN: ${{ secrets.NOAA_TOKEN }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up R
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: "4.5.0"

      - name: Install system dependencies for R packages
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            git \
            libcurl4-openssl-dev \
            libfontconfig1-dev \
            libfreetype6-dev \
            libfribidi-dev \
            libgit2-dev \
            libharfbuzz-dev \
            libjpeg-dev \
            libpng-dev \
            libssl-dev \
            libtiff5-dev \
            libv8-dev \
            libxml2-dev \
            wget

      # - name: Install R dependencies
      #   run: |
      #     install.packages('devtools')
      #     devtools::install_deps(dependencies = TRUE)

      - name: Run script
        run: Rscript tests/test_bsyncr.R
